// ## Problem 2: Design Hashmap (https://leetcode.com/problems/design-hashmap/)

// Time Complexity :
// Space Complexity :
// Did this code successfully run on Leetcode :
// Any problem you faced while coding this :

// Implementing hashing for the base implementation Collision handling is done using linear chaining

// Your code here along with comments explaining your approach
 class MyHashMap {

 }